CREATE TABLE IF NOT EXISTS memna_areas (
    id_memna_areas INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL,
    baja BOOLEAN NOT NULL,
    options JSON,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS memna_contenidos (
    id_memna_contenidos INT PRIMARY KEY AUTO_INCREMENT,
    fk_id_memna_areas INT,
    año INT NOT NULL,
    titulo TEXT NOT NULL,
    contenido TEXT,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    FOREIGN KEY (fk_id_memna_areas) REFERENCES memna_areas(id_memna_areas) ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX (fk_id_memna_areas)
);

CREATE TABLE IF NOT EXISTS mail_juguete (
    id INT PRIMARY KEY AUTO_INCREMENT,
    mail_institucion VARCHAR(50) UNIQUE,
    mail_personal VARCHAR(50) UNIQUE,
    nombre VARCHAR(50),
    apellido VARCHAR(50),
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);